Add deployment steps for WWI-mirror Database with status polling and connection creation

diff --git a/.github/workflows/deploy-fabric-accelerator.yml b/.github/workflows/deploy-fabric-accelerator.yml
--- a/.github/workflows/deploy-fabric-accelerator.yml
+++ b/.github/workflows/deploy-fabric-accelerator.yml
@@ -56,7 +56,7 @@ jobs:
      OLD_MASTER_LEVEL2_TRANSFORM_PIPELINE_LOGICAL_ID: 29ca711a-e20f-457c-a619-35b0310193ad
      OLD_OPTIMIZE_DELTA_TABLES_NOTEBOOK_ID: dcbe357b-2a94-4d28-a21f-8e2300e33f89
      OLD_L1_TRANSFORM_GENERIC_NOTEBOOK_ID: 3e035f81-2c25-416b-9009-b7ba22e444ab
-     OLD_WWI_MIRROR_DB_ID: 70663ea8-e214-4089-80dd-5c36815cb9a6
+     OLD_WWI_MIRROR_DB_ID: bed6498b-903b-40b3-afae-421411396a4a
 
     runs-on: ubuntu-latest
     steps:
@@ -169,24 +169,80 @@ jobs:
                 fab api -X post "connections/$connectionID/roleAssignments" -i "$rolejson" --show_headers
 
               fi
-        
-        # # Create Mirror ASQL database connection if it does not exist
-        # - name: Create Mirror ASQL DB Connection if it does not exist
-        #   run: |
-        #       MirrorASQLConnExists=$(fab exists .connections/"${WORKSPACE_NAME}-WWI-mirror".Connection | tr -d '[:space:]')
-        #       echo "MirrorASQLConnExists: $MirrorASQLConnExists"
-        #       if [ "$MirrorASQLConnExists" != "*true" ]; then
-        #         server="${{ secrets.WWI_SERVER }}"
-        #         database="${{ secrets.WWI_DATABASE }}"
-        #         echo "Creating connection for server: $server and database: $database"
-        #         fab create .connections/"${WORKSPACE_NAME}-WWI-mirror".Connection -P connectionDetails.creationMethod=SQL,connectionDetails.type=SQL,connectionDetails.parameters.server=$server,connectionDetails.parameters.database=$database,credentialDetails.type=ServicePrincipal,credentialDetails.servicePrincipalClientId=${{ secrets.ACTION_SPN_CLIENTID }},credentialDetails.servicePrincipalSecret=${{ secrets.ACTION_SPN_SECRET }},credentialDetails.tenantid=${{ secrets.TENANT_ID }} 
-        #         connectionID=$(fab get .connections/"${WORKSPACE_NAME}-WWI-mirror".Connection -q id| tr -d '\r')
+       # Deploy WWI-mirror Database
+        - name: Deploy WWI-mirror Database
+          run: |
+            set -euo pipefail
+            MirrorDBExists=$(fab exists $WORKSPACE_NAME.Workspace/WWI-mirror.MirroredDatabase | tr -d '[:space:]')
+          
+            if [ "$MirrorDBExists" != "*true" ]; then
+                mirroring=$(jq '.' "${GITHUB_WORKSPACE}/workspace/mirror/WideWorldImporters-mirror.MirroredDatabase/mirroring.json" | base64)
+                folderId=$(fab get $WORKSPACE_NAME.Workspace/mirror.Folder -q id | tr -d '\r')
+                jsonPayload=$(jq -n \
+                          --arg displayName "WWI-mirror" \
+                          --arg payload "$mirroring" \
+                          --arg folderId "$folderId" \
+                          '{"displayName": $displayName,"definition": {"parts":[{"path": "mirroring.json","payload": $payload,"payloadType": "InlineBase64"}]},"folderId": $folderId}')
+                response=$(fab api -X post "workspaces/$NEW_FABRIC_WORKSPACE_ID/mirroredDatabases" -i "$jsonPayload" --show_headers)
+                echo "$response"
+                status_code=$(echo "$response" | jq -r '.status_code')
                 
-        #         rolejson=$(jq -n --arg id "$WORKSPACE_ADMIN_ID" --arg type "${WORKSPACE_ADMIN_TYPE^}" '{"principal": {"id": $id, "type": $type}, "role": "Owner"}')         
-        #         echo "Assigning role to connection: $rolejson"
-        #         fab api -X post "connections/$connectionID/roleAssignments" -i "$rolejson" --show_headers
+                if [ "$status_code" = "201" ]; then
+                  echo "WWI-mirror Database deployed successfully."
+                else
+                  echo "Deployment of WWI-mirror Database failed with status code: $status_code">&2
+                  exit 1
+                fi
+            fi
+            
+            NEW_WWI_MIRROR_DB_ID=$(fab get $WORKSPACE_NAME.Workspace/WWI-mirror.MirroredDatabase -q id | tr -d '\r')
+            echo "NEW_WWI_MIRROR_DB_ID=$NEW_WWI_MIRROR_DB_ID" >> $GITHUB_ENV
 
-        #       fi
+            # Poll mirroring status until no longer Initializing
+            echo "Waiting for WWI-mirror to initialize..."
+            while :; do
+              response=$(fab api -X post "workspaces/$NEW_FABRIC_WORKSPACE_ID/mirroredDatabases/$NEW_WWI_MIRROR_DB_ID/getMirroringStatus" --show_headers)
+              echo "$response"
+              status=$(echo "$response" | jq -r '.text.status')
+              echo "Mirroring status: $status"
+              [ "$status" != "Initializing" ] && break
+              sleep 30
+            done
+            echo "Mirroring status is now: $status"
+
+            # Start Mirroring
+            echo "Starting WWI-mirror..."
+            response=$(fab api -X post "workspaces/$NEW_FABRIC_WORKSPACE_ID/mirroredDatabases/$NEW_WWI_MIRROR_DB_ID/startMirroring" --show_headers)
+            echo "$response"
+            status_code=$(echo "$response" | jq -r '.status_code')
+
+            if [ "$status_code" = "200" ]; then
+              echo "WWI-mirror Database mirroring started successfully."
+            else
+              echo "Starting mirroring for WWI-mirror Database failed with status code: $status_code">&2
+              exit 1
+            fi
+        
+
+        # Create WWI-mirror database connection if it does not exist
+        - name: Create WWI-mirror Connection if it does not exist
+          run: |
+              MirrorASQLConnExists=$(fab exists .connections/"${WORKSPACE_NAME}-WWI-mirror".Connection | tr -d '[:space:]')
+              echo "MirrorASQLConnExists: $MirrorASQLConnExists"
+              if [ "$MirrorASQLConnExists" != "*true" ]; then
+                server=$(fab get $WORKSPACE_NAME.Workspace/WWI-mirror.MirroredDatabase -q properties.sqlEndpointProperties.connectionString | tr -d '\r')
+                database="WWI-mirror"
+                echo "Creating connection for server: $server and database: $database"
+                fab create .connections/"${WORKSPACE_NAME}-WWI-mirror".Connection -P connectionDetails.creationMethod=SQL,connectionDetails.type=SQL,connectionDetails.parameters.server=$server,connectionDetails.parameters.database=$database,credentialDetails.type=ServicePrincipal,credentialDetails.servicePrincipalClientId=${{ secrets.ACTION_SPN_CLIENTID }},credentialDetails.servicePrincipalSecret=${{ secrets.ACTION_SPN_SECRET }},credentialDetails.tenantid=${{ secrets.TENANT_ID }} 
+               
+                connectionID=$(fab get .connections/"${WORKSPACE_NAME}-WWI-mirror".Connection -q id| tr -d '\r')
+                echo "NEW_WWI_MIRROR_DB_ID=$connectionID" >> $GITHUB_ENV
+                
+                rolejson=$(jq -n --arg id "$WORKSPACE_ADMIN_ID" --arg type "${WORKSPACE_ADMIN_TYPE^}" '{"principal": {"id": $id, "type": $type}, "role": "Owner"}')         
+                echo "Assigning role to connection: $rolejson"
+                fab api -X post "connections/$connectionID/roleAssignments" -i "$rolejson" --show_headers
+
+              fi
 
           # Create Medallion Layers if they do not exist
         - name: Create Medallion Layers if they do not exist
@@ -270,6 +326,11 @@ jobs:
               grep --null -rl "$OLD_WIDE_WORLD_IMPORTERS_CONNECTION_ID" "${GITHUB_WORKSPACE}/workspace" | tr '\0' '\n'
               grep --null -rl $OLD_WIDE_WORLD_IMPORTERS_CONNECTION_ID ${GITHUB_WORKSPACE}/workspace | xargs -0 sed -i "s/$OLD_WIDE_WORLD_IMPORTERS_CONNECTION_ID/$WIDE_WORLD_IMPORTERS_CONNECTION_ID/g"
 
+              echo "Files to be updated from $OLD_WWI_MIRROR_DB_ID to $NEW_WWI_MIRROR_DB_ID"
+              grep --null -rl "$OLD_WWI_MIRROR_DB_ID" "${GITHUB_WORKSPACE}/workspace" | tr '\0' '\n'
+              grep --null -rl $OLD_WWI_MIRROR_DB_ID ${GITHUB_WORKSPACE}/workspace | xargs -0 sed -i "s/$OLD_WWI_MIRROR_DB_ID/$NEW_WWI_MIRROR_DB_ID/g"
+
+
               echo "Files to be updated with new Tenant ID"
               grep --null -rl "$OLD_TENANT_ID" "${GITHUB_WORKSPACE}/workspace" | tr '\0' '\n'
               grep --null -rl $OLD_TENANT_ID ${GITHUB_WORKSPACE}/workspace | xargs -0 sed -i "s/$OLD_TENANT_ID/${{ secrets.TENANT_ID }}/g"
@@ -333,59 +394,7 @@ jobs:
             grep --null -rl "$OLD_L1_TRANSFORM_GENERIC_NOTEBOOK_ID" "${GITHUB_WORKSPACE}/workspace" | tr '\0' '\n'
             grep --null -rl $OLD_L1_TRANSFORM_GENERIC_NOTEBOOK_ID ${GITHUB_WORKSPACE}/workspace | xargs -0 sed -i "s/$OLD_L1_TRANSFORM_GENERIC_NOTEBOOK_ID/$NEW_L1_TRANSFORM_GENERIC_NOTEBOOK_ID/g"
 
-        # Deploy WWI-mirror Database
-        - name: Deploy WWI-mirror Database
-          run: |
-            set -euo pipefail
-            MirrorDBExists=$(fab exists $WORKSPACE_NAME.Workspace/WWI-mirror.MirroredDatabase | tr -d '[:space:]')
-          
-            if [ "$MirrorDBExists" != "*true" ]; then
-                mirroring=$(jq '.' "${GITHUB_WORKSPACE}/workspace/mirror/WideWorldImporters-mirror.MirroredDatabase/mirroring.json" | base64)
-                folderId=$(fab get $WORKSPACE_NAME.Workspace/mirror.Folder -q id | tr -d '\r')
-                jsonPayload=$(jq -n \
-                          --arg displayName "WWI-mirror" \
-                          --arg payload "$mirroring" \
-                          --arg folderId "$folderId" \
-                          '{"displayName": $displayName,"definition": {"parts":[{"path": "mirroring.json","payload": $payload,"payloadType": "InlineBase64"}]},"folderId": $folderId}')
-                response=$(fab api -X post "workspaces/$NEW_FABRIC_WORKSPACE_ID/mirroredDatabases" -i "$jsonPayload" --show_headers)
-                echo "$response"
-                status_code=$(echo "$response" | jq -r '.status_code')
-                
-                if [ "$status_code" = "201" ]; then
-                  echo "WWI-mirror Database deployed successfully."
-                else
-                  echo "Deployment of WWI-mirror Database failed with status code: $status_code">&2
-                  exit 1
-                fi
-            fi
-            
-            NEW_WWI_MIRROR_DB_ID=$(fab get $WORKSPACE_NAME.Workspace/WWI-mirror.MirroredDatabase -q id | tr -d '\r')
-            echo "NEW_WWI_MIRROR_DB_ID=$NEW_WWI_MIRROR_DB_ID" >> $GITHUB_ENV
 
-            # Poll mirroring status until no longer Initializing
-            echo "Waiting for WWI-mirror to initialize..."
-            while :; do
-              response=$(fab api -X post "workspaces/$NEW_FABRIC_WORKSPACE_ID/mirroredDatabases/$NEW_WWI_MIRROR_DB_ID/getMirroringStatus" --show_headers)
-              echo "$response"
-              status=$(echo "$response" | jq -r '.text.status')
-              echo "Mirroring status: $status"
-              [ "$status" != "Initializing" ] && break
-              sleep 30
-            done
-            echo "Mirroring status is now: $status"
-
-            # Start Mirroring
-            echo "Starting WWI-mirror..."
-            response=$(fab api -X post "workspaces/$NEW_FABRIC_WORKSPACE_ID/mirroredDatabases/$NEW_WWI_MIRROR_DB_ID/startMirroring" --show_headers)
-            echo "$response"
-            status_code=$(echo "$response" | jq -r '.status_code')
-
-            if [ "$status_code" = "200" ]; then
-              echo "WWI-mirror Database mirroring started successfully."
-            else
-              echo "Starting mirroring for WWI-mirror Database failed with status code: $status_code">&2
-              exit 1
-            fi
 
       # Deploy Pipeline wwi-elt-framework
         - name: Deploy Pipeline wwi-elt-framework
